#!/usr/bin/php -Cq
<?php
require_once __DIR__ . '/../zendsearch/vendor/autoload.php';

#On récupère le nom de l'index
$indexName = "searchEngine";
#Puis l'élément à rechercher
$fileName = $_GET["name"];

#Ensuite, test si l'index existe ou non
if(!file_exists($indexName))
{
	echo "Erreur, index inexistant". PHP_EOL;
}
else if($fileName != null)
{	
	#On créé ensuite un nouveau document
	$doc = new \ZendSearch\Lucene\Document();
	#Auquel on va ajouter les champs souhaités
	$doc->addField(\ZendSearch\Lucene\Document\Field::text('title', $pdfDoc->properties['Title']));
	$doc->addField(\ZendSearch\Lucene\Document\Field::text('creationDate', $pdfDoc->properties['CreationDate']));
	
	try{
		#On ouvre notre index, on recherche si notre document possède un attribut correspondant au chemin de ce fichier.
		$index = \ZendSearch\Lucene\Lucene::open($indexName);
		$resultFind = $index->find("filename:".$fileName);
		
		#On test si notre fichier est déjà indexé ou pas.
		#Si il n'est pas déjà indexé, on le fait
		if(count($resultFind) ==0){
			$doc->addField(\ZendSearch\Lucene\Document\Field::text('filename', $fileName));
			$index->addDocument($doc);
		}
		#Sinon, on arrête le traitement.
		else{
			echo "Erreur, document déjà existant" . PHP_EOL;
		}
		
		$index->optimize();
	}
	catch(\ZendSearch\Lucene\Exception\RuntimeException $e){
		echo "Index erreur, fin de l'operation" . PHP_EOL;
	}
}


#Fonction qui lit le contenu du fichier odt, et l'ajoute au document
function parseContentOdt($contentPath, $doc){
	$reader = new XMLReader();
	$reader->open($contentPath);
	
	#On se place à la racine du contenu
	while ($reader->read() && $reader->name !== 'office:text');
	
	#Tant que nous sommes pas rendu à la fin du document, on parcourt le fichier pour récupérer le contenu
	while ($reader->read() && $reader->name !== 'office:text'){
		if(strpos($reader->name, 'text:p') !== false && $reader->nodeType == XMLReader::ELEMENT){
			$reader->read();
			$doc->addField(\ZendSearch\Lucene\Document\Field::text('body', $reader->value));
		}
	}
	$reader->close();
	return $doc;
}


