SELECT ?alt  ?type_alt ?title  where { 
                  ?alt <http://www.w3.org/1999/02/22-rdf-syntax-ns#_1> ?title
	?alt <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type_alt
	?musique 
	?x <http://purl.org/dc/elements/1.1/title> ?alt
}